# Generated by Django 2.0.7 on 2018-07-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=photos.models.user_directory_path)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('authorized', models.BooleanField(default=False)),
                ('quantity_like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
