# Generated by Django 2.0.7 on 2018-07-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180719_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
    ]
